import {
  EnumKeys,
  EnumKeysFirebase,
  EnumServices,
  EnumTabs,
  EnumTypesOptions,
} from "../../../../../../types/enums";

const SubCategoryFirebase = {
  category: EnumTabs.services,
  category_label: "Serviços",
  sub_category: EnumServices.firebase,
  sub_category_label: "Firebase",
  disabled: false,
  tip: "",
};
export const ForceRedefinitionValues = [
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.collection,
  },
];
export const ServiceFirebase: IOptionConfig2[] = [
  {
    ...SubCategoryFirebase,
    key: EnumKeys.status,
    value: false,
    label: "Usar serviço Firebase",
    description:
      "Define se o serviço Firebase será executado. \nLembre-se: Para usar o serviço de PIX esse serviço precisa estar ativo.",
    type: EnumTypesOptions.boolean,
    validate_keys: [
      {
        category: EnumTabs.services,
        sub_category: EnumServices.pix,
        key: EnumKeys.status,
        onvalue: false,
        keyvalue: true,
        block: true,
        message:
          "Esse recurso está sendo usado pelo serviço de PIX, desative-o antes para prosseguir.",
      },
    ],
  },

  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.validate_ip,
    value: false,
    label: EnumKeysFirebase.validate_ip,
    description:
      "Define se o IP local vai ser comparado com o do recebido no evento de cobrança.",
    type: EnumTypesOptions.boolean,
  },

  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.collection,
    value: "cobrancas-pix",
    label: EnumKeysFirebase.collection,
    description: "Nome da coleção dos registros do  Pix",
    type: EnumTypesOptions.text,
  },

  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.liberation_key,
    value: "liberacaokey",
    label: EnumKeysFirebase.liberation_key,
    description: "Nome da coleção dos registros do  Pix",
    type: EnumTypesOptions.text,
  },
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.cnpj,
    value: "cnpj",
    label: EnumKeysFirebase.cnpj,
    description: "Campo CNPJ do  Pix",
    type: EnumTypesOptions.text,
  },

  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.ip,
    value: "ip",
    label: EnumKeysFirebase.ip,
    description: "Campo IP do  Pix",
    type: EnumTypesOptions.text,
  },
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.username,
    value: "nomeusuario",
    label: EnumKeysFirebase.username,
    description: "Campo Usuário Conectado Windows do  Pix",
    type: EnumTypesOptions.text,
  },
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.machine_name,
    value: "estacaotrabalho",
    label: EnumKeysFirebase.machine_name,
    description: "Campo Estação Conectada Windows do Pix",
    type: EnumTypesOptions.text,
  },
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.id,
    value: "txid",
    label: EnumKeysFirebase.id,
    description: "Campo ID do  Pix",
    type: EnumTypesOptions.text,
  },
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.price,
    value: "valor",
    label: EnumKeysFirebase.price,
    description: "Campo Valor do  Pix",
    type: EnumTypesOptions.text,
  },
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.portion,
    value: "parcela",
    label: EnumKeysFirebase.portion,
    description: "Campo Parcela do  Pix",
    type: EnumTypesOptions.text,
  },
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.img,
    value: "imagemqrcode",
    label: EnumKeysFirebase.img,
    description: "Campo Imagem Base64 do Pix",
    type: EnumTypesOptions.text,
  },
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.link,
    value: "linkqrcode",
    label: EnumKeysFirebase.link,
    description: "Campo Link Copia e Cola do Pix",
    type: EnumTypesOptions.text,
  },
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.phone,
    value: "telefone",
    label: EnumKeysFirebase.phone,
    description: "Campo Telefone do Pix",
    type: EnumTypesOptions.text,
  },
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.status,
    value: "status",
    label: EnumKeysFirebase.status,
    description: "Campo Status do Pix",
    type: EnumTypesOptions.text,
  },
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.message,
    value: "mensagem",
    label: EnumKeysFirebase.message,
    description: "Campo Mensagem do Pix",
    type: EnumTypesOptions.text,
  },
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.created_at,
    value: "datacriacao",
    label: EnumKeysFirebase.created_at,
    description: "Campo Data de Criação do Pix",
    type: EnumTypesOptions.text,
  },
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.error,
    value: "error",
    label: EnumKeysFirebase.error,
    description: "Campo de dados de Erro do Pix",
    type: EnumTypesOptions.text,
  },
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.status_awaiting_payment,
    value: "ativo",
    label: EnumKeysFirebase.status_awaiting_payment,
    description: "Status do Pix ABERTO",
    type: EnumTypesOptions.text,
  },
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.status_confirmed_payment,
    value: "concluido",
    label: EnumKeysFirebase.status_confirmed_payment,
    description: "Status do Pix FINALIZADO",
    type: EnumTypesOptions.text,
  },
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.status_canceled,
    value: "cancelado",
    label: EnumKeysFirebase.status_canceled,
    description: "Status do Pix CANCELADO",
    type: EnumTypesOptions.text,
  },
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.status_canceled_system,
    value: "cancelado-sistema",
    label: EnumKeysFirebase.status_canceled,
    description: "Status do Pix CANCELADO pelo Sistema.",
    type: EnumTypesOptions.text,
  },
  {
    ...SubCategoryFirebase,
    key: EnumKeysFirebase.status_canceled_client,
    value: "cancelado-cliente",
    label: EnumKeysFirebase.status_canceled_client,
    description: "Status do Pix CANCELADO pelo Cliente.",
    type: EnumTypesOptions.text,
  },
];
